### ISSUE TITLE
What about moving this logic to the model?

### ISSUE THREAD

**Issue by landtax** [lacazeto/sinatra-app-temp#1]
I'd suggest to:
* move item to its own file
* move this logic to a before validation hook
https://github.com/lacazeto/sinatra-app-temp/blob/8aba337a4d5e2e2aad33a72319a3cbeb65c350ab/models/list.rb#L14

**Comment by lacazeto** [comment]
Moved, but this caused rubocop to start complaining about the new code.
Tried refactoring using unless block or unless inline, but rubocop complains both ways.
